config/application.config.php
The `Application` module is registered a few lines further down the line again, once should be enough.
=> Fix: Remove duplicate entry in array of modules

config/autoload/cache.local.php.dist, module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/Controller/IndexController.php, module/ZfModule/src/ZfModule/Controller/IndexControllerFactory.php, module/ZfModule/src/ZfModule/Module.php
the github client already have a cache logic implement and this stuff can dumped out of the controller logic
=> Fix: Removed the cache logic from module controller

composer.json, composer.lock, module/Application/config/module.config.php, module/Application/src/Application/Service/HtmlPurifierFactory.php, module/Application/src/Application/View/Helper/SanitizeHtml.php, module/Application/src/Application/View/Helper/SanitizeHtmlFactory.php, module/Application/test/ApplicationTest/Integration/Service/HtmlPurifierTest.php, module/Application/test/ApplicationTest/Integration/View/Helper/SanitizeHtmlTest.php, module/Application/test/ApplicationTest/Service/HtmlPurifierTest.php, module/Application/view/application/index/index.phtml, module/Application/view/application/search/index.phtml, module/Application/view/layout/layout-small-header.phtml, module/Application/view/layout/layout.phtml, module/User/view/user/helper/new-users.phtml, module/User/view/user/helper/user-organizations.phtml, module/ZfModule/view/zf-module/helper/composer-view.phtml, module/ZfModule/view/zf-module/helper/module-description.phtml, module/ZfModule/view/zf-module/helper/module-view.phtml, module/ZfModule/view/zf-module/helper/new-module.phtml, module/ZfModule/view/zf-module/index/view.phtml
=> [WIP] Fix/Added escape helper to view output

config/application.config.php, config/autoload/cache.local.php.dist, config/autoload/database.local.php.dist, config/autoload/github.local.php.dist, config/autoload/global.php, config/autoload/scn-social-auth.global.php, config/autoload/zfcuser.global.php, config/development.config.php.dist, module/Application/config/module.config.php, module/Application/src/Application/Controller/IndexController.php, module/Application/src/Application/Controller/SearchController.php, module/Application/src/Application/Module.php, module/Application/src/Application/Service/RepositoryRetriever.php, module/Application/test/ApplicationTest/Integration/Controller/IndexControllerTest.php, module/User/config/module.config.php, module/User/src/User/Mapper/User.php, module/User/src/User/Module.php, module/User/src/User/View/Helper/NewUsers.php, module/User/src/User/View/Helper/UserOrganizations.php, module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/Controller/IndexController.php, module/ZfModule/src/ZfModule/Mapper/Module.php, module/ZfModule/src/ZfModule/Module.php, module/ZfModule/src/ZfModule/View/Helper/ComposerView.php, module/ZfModule/src/ZfModule/View/Helper/ListModule.php, module/ZfModule/src/ZfModule/View/Helper/ModuleDescription.php, module/ZfModule/src/ZfModule/View/Helper/ModuleView.php, module/ZfModule/src/ZfModule/View/Helper/NewModule.php, module/ZfModule/src/ZfModule/View/Helper/OwnerModuleList.php
Since this is what `composer.json` says
```json
{
"require": {
"php": ">=5.5.0"
}
}
```
I guess it makes a lot of sense to use short array syntax.
Used https://github.com/thomasbachem/php-short-array-syntax-converter for this.
=> Enhancement: Use short array syntax

module/Application/test/ApplicationTest/Integration/Controller/IndexControllerTest.php, module/Application/test/ApplicationTest/Integration/Controller/SearchControllerTest.php, module/Application/test/ApplicationTest/Integration/Util/Bootstrap.php
=> Enhancement: Leverage AbstractHttpControllerTestCase

module/User/config/module.config.php, module/User/src/User/GitHub/LoginListener.php, module/User/src/User/Module.php, module/User/test/UserTest/GitHub/LoginListenerTest.php, module/User/test/UserTest/Integration/GitHub/LoginListenerTest.php
As promised in #286 this PR moves registration listener from closure in `User\Module` to separate listener class. There is both unit and integration test case to assure that listener is attached and `registerViaProvider` event triggered in `ScnSocialAuth` module.
I still have to find a way how to update existing local user profile from actual GitHub data after login.
@Ocramius could you please provide code review?
=> github registration listener refactoring + tests

module/ZfModule/src/ZfModule/Controller/IndexController.php
The result of the expression is never used.
=> Fix: Expression result unused

module/ZfModule/src/ZfModule/Controller/IndexController.php
fixes #182 
fixes #158 
but we need a solution in the future where such repos gets deleted from the db
=> Fix: added github repo exists check

composer.json, composer.lock
With composer minimum stabilty dev:
* zf and many others is loaded from master (unstable),
* loading time from branch (no tag) it's sooooo long...
=> Remove composer minimum stability

config/development.config.php.dist
Drop AssetManager module from dev-mode modules as it's loaded already in application.config.php
=> Drop AssetManager module from dev-mode

.travis.yml, composer.json, composer.lock
Since there seems to be some consensus on removing `phpmd/phpmd`, this PR removes it.
=> Fix: Remove phpmd/phmd

composer.json, composer.lock, module/Application/config/module.config.php, module/Application/src/Application/Module.php, module/Application/src/Application/Service/ErrorHandlingService.php, module/Application/src/Application/Service/ErrorHandlingServiceFactory.php, module/Application/src/Application/Service/LoggerFactory.php, module/Application/test/ApplicationTest/Integration/Service/ErrorHandlingServiceTest.php, module/Application/test/ApplicationTest/Integration/Service/LoggerFactoryTest.php, module/Application/test/ApplicationTest/Service/ErrorHandlingServiceTest.php
=> Enhancement: Use Monolog logger with RotatingFileHandler

module/Application/Module.php, module/User/Module.php, module/ZfModule/Module.php
This PR
Follows @Ocramius' comment, see [`Zend\ModuleManager\Listener\ModuleResolverListener`](https://github.com/zendframework/zf2/blob/master/library/Zend/ModuleManager/Listener/ModuleResolverListener.php#L23-L34).
Not sure when this was changed?!
=> Fix: Remove useless files

module/Application/config/module.config.php, module/Application/test/ApplicationTest/Integration/Controller/IndexControllerTest.php, module/Application/test/ApplicationTest/Integration/Controller/SearchControllerTest.php, module/ZfModule/config/module.config.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/IndexControllerTest.php
I think I accidentally the whole thing.
This PR
Related to #294.
=> Enhancement: Leverage class keyword as service identifiers for controllers

module/User/config/module.config.php
=> Fix: Remove useless configuration

module/User/src/User/Module.php, module/ZfModule/src/ZfModule/Mapper/Module.php
=> Fix: Remove PHPMD annotations

module/User/config/module.config.php, module/User/src/User/Controller/UserController.php, module/User/test/UserTest/Integration/Controller/UserControllerTest.php, module/User/view/zfc-user/user/index.phtml, module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/Mvc/Controller/Plugin/ListModule.php, module/ZfModule/src/ZfModule/Mvc/Controller/Plugin/ListModuleFactory.php
=> Fix: View helper should actually be a controller plugin

module/Application/view/application/index/index.phtml
=> Fix: Misspelled method is actually used

module/Application/view/application/index/index.phtml, module/Application/view/application/search/index.phtml
=> Feature: added message for none results on search

module/User/test/UserTest/GitHub/LoginListenerTest.php
=> Fix: Directly attach to SharedEventManager instance

module/Application/config/module.config.php, module/User/config/module.config.php
=> Fix: Clean up template maps

module/User/src/User/View/Helper/NewUsers.php, module/User/src/User/View/Helper/UserOrganizations.php, module/ZfModule/src/ZfModule/View/Helper/ComposerView.php, module/ZfModule/src/ZfModule/View/Helper/ModuleDescription.php, module/ZfModule/src/ZfModule/View/Helper/ModuleView.php, module/ZfModule/src/ZfModule/View/Helper/TotalModules.php
=> Fix: Update doc-blocks of view helpers

module/User/src/User/View/Helper/NewUsers.php, module/User/src/User/View/Helper/UserOrganizations.php, module/User/test/UserTest/View/Helper/NewUsersTest.php, module/User/test/UserTest/View/Helper/UserOrganizationsTest.php, module/ZfModule/src/ZfModule/View/Helper/ComposerView.php, module/ZfModule/src/ZfModule/View/Helper/ModuleDescription.php, module/ZfModule/src/ZfModule/View/Helper/ModuleView.php, module/ZfModule/src/ZfModule/View/Helper/NewModule.php, module/ZfModule/src/ZfModule/View/Helper/TotalModules.php, module/ZfModule/test/ZfModuleTest/View/Helper/ComposerViewTest.php, module/ZfModule/test/ZfModuleTest/View/Helper/ModuleDescriptionTest.php, module/ZfModule/test/ZfModuleTest/View/Helper/ModuleViewTest.php, module/ZfModule/test/ZfModuleTest/View/Helper/NewModuleTest.php, module/ZfModule/test/ZfModuleTest/View/Helper/TotalModulesTest.php
=> Fix: Simplify rendering of view scripts in view helpers

module/ZfModule/src/ZfModule/View/Helper/ModuleDescription.php, module/ZfModule/test/ZfModuleTest/View/Helper/ModuleDescriptionTest.php, module/ZfModule/view/zf-module/helper/module-description.phtml, module/ZfModule/view/zf-module/index/view.phtml
=> Fix: Pass repository instead of array into view helper

.travis.yml
=> Enhancement: Cache dependencies installed with Composer on Travis

module/Application/test/ApplicationTest/Integration/Util/AuthenticationTrait.php, module/User/test/UserTest/Integration/Controller/UserControllerTest.php, module/ZfModule/src/ZfModule/Controller/IndexController.php, module/ZfModule/src/ZfModule/Mapper/Module.php, module/ZfModule/src/ZfModule/Service/Module.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/IndexControllerTest.php
=> Enhancement: Clean up ZfModule\Controller\IndexController

module/ZfModule/test/ZfModuleTest/Mapper/ModuleHydratorTest.php
=> Enhancement: Assert InvalidArgumentExceptions are thrown

module/User/view/scn-social-auth/user/login.phtml, module/User/view/user/helper/user-organizations.phtml, module/User/view/zfc-user/user/index.phtml
=> Fix: github vs GitHub

module/User/view/zfc-user/user/index.phtml
This PR
Compare `No modules was submitted yet` to `No modules have been submitted yet`.
=> Fix: Wording of message in case no modules have been submitted

module/User/src/User/Mapper/UserFactory.php, module/User/src/User/Mapper/UserHydrator.php
=> Fix: Remove useless User\Mapper\UserHydrator

module/ZfModule/src/ZfModule/Service/Module.php, module/ZfModule/test/ZfModuleTest/Service/ModuleTest.php
=> Enhancement: Increase coverage for ZfModule\Service\Module

module/User/view/scn-social-auth/user/login.phtml, module/User/view/zfc-user/user/index.phtml
=> Fix: Use alternative syntax in view scripts

module/ZfModule/src/ZfModule/Mapper/Module.php, module/ZfModule/src/ZfModule/Mapper/ModuleInterface.php
This PR
:bulb: Not so sure what we'd need `ZfModule\Mapper\ModuleInterface` for, there's currently only one implementation anyway.
=> Fix: Remove method which is never used

module/ZfModule/config/module.config.php
=> Fix: Remove plugin configuration for non-existent plugin

module/ZfModule/src/ZfModule/Service/Module.php, module/ZfModule/test/ZfModuleTest/Service/ModuleTest.php
This PR
Fixes #128.
Fixes #199.
Fixes #246.
* create a repository on GitHub with the same name as a registered on, e.g., `ZF2-AcYaml` https://github.com/acelaya/ZF2-AcYaml, I did here https://github.com/localheinz/ZF2-AcYaml
* sign in with GitHub to http://modules.zendframework.com
* navigate to http://modules.zendframework.com/user
=> Fix: When validating repositories, attempt to find by html_url, not by name

module/User/src/User/Controller/UserController.php, module/User/view/zfc-user/user/index.phtml, module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/Controller/IndexController.php, module/ZfModule/src/ZfModule/Service/Module.php, module/ZfModule/src/ZfModule/View/Helper/ModuleView.php, module/ZfModule/src/ZfModule/View/Helper/Repository.php, module/ZfModule/test/ZfModuleTest/Integration/View/Helper/RepositoryTest.php, module/ZfModule/test/ZfModuleTest/Service/ModuleTest.php, module/ZfModule/test/ZfModuleTest/View/Helper/ModuleViewTest.php, module/ZfModule/test/ZfModuleTest/View/Helper/RepositoryTest.php, module/ZfModule/view/zf-module/helper/module-view.phtml, module/ZfModule/view/zf-module/helper/repository.phtml, module/ZfModule/view/zf-module/index/index.phtml
This PR aims at simplifying the usage of the `ZfModule\View\Helper\ModuleView` and effectively
Follows https://github.com/zendframework/modules.zendframework.com/pull/384#discussion_r24778491.
=> Enhancement: Simplify usage of ModuleView view helper

module/Application/src/Application/Controller/IndexControllerFactory.php, module/Application/src/Application/Controller/SearchControllerFactory.php, module/Application/test/ApplicationTest/Integration/Controller/IndexControllerTest.php, module/Application/test/ApplicationTest/Integration/Controller/SearchControllerTest.php, module/User/src/User/Controller/UserControllerFactory.php, module/User/test/UserTest/Integration/Controller/UserControllerTest.php, module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/Controller/IndexControllerFactory.php, module/ZfModule/src/ZfModule/Service/ModuleFactory.php, module/ZfModule/src/ZfModule/View/Helper/NewModuleFactory.php, module/ZfModule/src/ZfModule/View/Helper/TotalModulesFactory.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/IndexControllerTest.php, module/ZfModule/test/ZfModuleTest/Integration/Mapper/ModuleHydratorTest.php, module/ZfModule/test/ZfModuleTest/Integration/Mapper/ModuleTest.php, module/ZfModule/test/ZfModuleTest/Integration/Service/ModuleTest.php
=> Enhancement: Use class keyword as service identifier in ZfModule module

module/Application/view/layout/layout-small-header.phtml, module/Application/view/layout/layout.phtml
The aim of this PR is to streamline the existing layouts in order to reduce duplication, so we can move on and actually change it without having to do in two places.
=> Enhancement: Streamline layouts and fix-up content

config/autoload/global.php
This PR
See http://modules.zendframework.com/user
=> Enhancement: Use small header layout in User module

.travis.yml, composer.lock, module/ZfModule/src/ZfModule/Delegators/EdpGithubClientAuthenticator.php
=> Fix: composer.lock is not up to date, build issues

module/Application/view/application/index/index.phtml, module/Application/view/application/search/index.phtml, module/ZfModule/src/ZfModule/Mapper/Module.php, module/ZfModule/test/ZfModuleTest/Integration/Mapper/ModuleTest.php, module/ZfModule/view/zf-module/helper/new-module.phtml
=> Enhancement: Also search by owner, split query into words

module/Application/view/layout/layout-small-header.phtml, module/Application/view/layout/layout.phtml, module/User/view/user/helper/user-organizations.phtml, module/User/view/zfc-user/user/index.phtml
=> Fix: BasePath helper accepts argument, prepends with /

module/Application/view/application/index/index.phtml, module/Application/view/layout/layout.phtml
This PR
:bulb: The aim of this PR is to make the diff between `layout/layout.phtml` and `layout/layout-small-header.phtml` smaller, in order to eventually get rid of a lot of duplication.
Follows #397.
=> Fix: Only load live-search resources when needed

module/Application/public/css/style.css, module/Application/view/layout/layout.phtml
This PR
Kind of working my way down from the top, as you can see!
=> Fix: Semantic markup for GitHub ribbon

module/ZfModule/view/zf-module/helper/composer-view.phtml
There is no `label-important` CSS class in [Bootstrap 3](http://getbootstrap.com/components/#labels) (was in [Bootstrap 2](http://getbootstrap.com/2.3.2/components.html#labels-badges)). Equivalent class in new version is `label-danger`.
=> Fix: Wrong CSS class for labels

composer.json, composer.lock
This PR
See https://github.com/zendframework/modules.zendframework.com/search?utf8=✓&q=IntlDateFormatter.
=> Fix: intl extension is required

module/ZfModule/src/ZfModule/Service/Module.php, module/ZfModule/test/ZfModuleTest/Service/ModuleTest.php
=> Hotfix: Added correct type comparison

module/ZfModule/src/ZfModule/Mapper/Module.php, module/ZfModule/src/ZfModule/Service/Module.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/IndexControllerTest.php, module/ZfModule/test/ZfModuleTest/Integration/Mapper/ModuleTest.php, module/ZfModule/test/ZfModuleTest/Service/ModuleTest.php
This PR
See https://github.com/zendframework/modules.zendframework.com/pull/416/files#r25241195.
=> Fix: Return null if nothing was found by Mapper\Module

module/ZfModule/src/ZfModule/Controller/IndexController.php
=> Fix: Method actually returns unregistered modules

composer.json, composer.lock
Update composer autoload to psr-4
=> Change composer autoload to psr-4

.gitignore, build.properties.dist, build.xml, composer.json, composer.lock
The aim of this PR is to ease the deployment process and replicate the current process. I believe we could reiterate on this and, as @GeeH suggested, sort out something with rollbacks and the like
This PR, however,
=> Enhancement: Deploy with Phing

README.md
=> Fix: Update README in regard to releases

build.properties.dist, build.xml
This PR
```
$ vendor/bin/phing deploy -Dtag=1.2.1
```
=> Enhancement: Allow to specify tag to deploy

composer.json, composer.lock
Not that it matters much, but this PR
specified in `composer.json`.
=> Fix: Package name and homepage in composer.json

.gitignore
=> Fix: Sort rules in .gitignore alphabetically

module/Application/src/Application/Controller/ContributorsControllerFactory.php
=> Fix: Add missing inline comments and doc-block

module/Application/view/application/contributors/index.phtml
This PR
See http://bootply.com/d08bOti6Zs.
=> Enhancement: Reponsiveness of contributors grid

module/Application/test/ApplicationTest/Service/RepositoryRetrieverTest.php
This PR
Follows #447.
Sorry, my bad!
=> Fix: GitHub API response for contributors

module/Application/config/module.config.php, module/Application/src/Application/Controller/ContributorsControllerFactory.php, module/Application/src/Application/View/Helper/GitHubRepositoryUrlFactory.php, module/Application/test/ApplicationTest/Integration/Controller/ContributorsControllerTest.php
=> Fix: Configuration key for GitHub repository

module/Application/config/module.config.php, module/Application/src/Application/Controller/ContributorsController.php, module/Application/src/Application/Controller/ContributorsControllerFactory.php, module/Application/src/Application/Entity/Repository.php, module/Application/src/Application/Service/GitHubRepositoryFactory.php, module/Application/src/Application/View/Helper/GitHubRepositoryUrl.php, module/Application/src/Application/View/Helper/GitHubRepositoryUrlFactory.php, module/Application/test/ApplicationTest/Entity/RepositoryTest.php, module/Application/test/ApplicationTest/Integration/Controller/ContributorsControllerTest.php, module/Application/test/ApplicationTest/Integration/Service/GitHubRepositoryTest.php, module/Application/test/ApplicationTest/View/Helper/GitHubRepositoryUrlTest.php
This PR
Follows https://github.com/zendframework/modules.zendframework.com/pull/447#discussion_r25689320.
=> Enhancement: Implement Entity\Repository

build.xml
This PR
:bulb: Other than that, the deployment script worked for deploying [1.2.1](https://github.com/zendframework/modules.zendframework.com/releases/tag/1.2.1)!
=> Fix: Sudo required for pulling in changes on server

module/ZfModule/src/ZfModule/Controller/IndexController.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/IndexControllerTest.php
Hi! This proposal is not a resolution of all problems but in this moment I think that there are only one target..
We make zf.modules usable..
Login, submit repos in the first step.. This proposal tries to "resolve" the rate limit problem.
See
* #349 
With this PR the list of repos is inconsistente because there are a lot of repos wrong (not zf2 modules).. But works and if you try to submit a wrong repo exists a check for that :smile: 
Now there are already problem if i try to submit a good module I have this expection
`Statement could not be executed (23000 - 1048 - Column 'module_id' cannot be null)`
But I don't remember the story of the `module_id` :calendar: 
This isn't the final resolution :)
=> List of repositories from Github

module/ZfModule/test/ZfModuleTest/Integration/Controller/UserControllerTest.php
=> Fix: Single quotes

module/ZfModule/test/ZfModuleTest/Integration/Controller/UserControllerTest.php
This PR
Follows #444.
Spotted in #462.
=> Fix: Integration test for User controller fails because of lack of mocking

module/Application/config/module.config.php
This PR
:bulb: This is probably a remainder of the Zend Skeleton application, isn't it?
=> Fix: Remove useless route definition

module/ZfModule/config/module.config.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/IndexControllerTest.php
=> Fix: Config key should be 'constraints' instead of 'constrains'

module/ZfModule/src/ZfModule/Controller/UserControllerFactory.php
This PR
:bulb: Yes, I stumbled upon this when renaming `Controller\IndexController` to `Controller\ModuleController`.
Related to #468.
=> Fix: Factory creates a UserController, not an IndexController

module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/Controller/ModuleController.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/ModuleControllerTest.php
This PR
:bulb: Controller should probably be named differently as well, e.g., `ModuleController`
=> Fix: organizationAction() should be listAction()

.travis.yml
as the page runs not on ``hhvm`` it should be marked as ``allow_failures``. 
this would also be required as of pr #421 and the ``hhvm`` exception bug in phpunit - as an fix is not landed in phpunit yet.
PHPUnit Bug: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/207
=> Enhancement: added hhvm as allow failure

.gitignore, phpunit.xml
This PR
:bulb: We're not using the code coverage data generated on Travis *yet*, so it's a waste of resources (and time). Removing the configuration significantly speeds up the tests, and if one is interested in code coverage, you can still specify a command line option or run the tests from within your favourite IDE™.
=> Fix: Do not collect code coverage . . . for now

module/Application/src/Application/Service/RepositoryRetriever.php, module/Application/test/ApplicationTest/Integration/Controller/ContributorsControllerTest.php, module/Application/test/ApplicationTest/Service/RepositoryRetrieverTest.php, module/Application/view/application/contributors/index.phtml
This PR
See https://github.com/zendframework/modules.zendframework.com/pull/447#discussion_r25690636.
=> Fix: Do not json_decode API response to associative array

module/Application/view/application/index/index.phtml, module/Application/view/layout/layout.phtml, module/ZfModule/config/module.config.php, module/ZfModule/src/ZfModule/View/Helper/TwitterWidget.php, module/ZfModule/view/zf-module/helper/twitter-widget-view.phtml, public/js/twitter-widget.js
Hi!
I opend a new twitter account [@zfmodules](https://twitter.com/zfmodules) for this site.
Ifttt tweet every new module updated
=> Widget Twitter account @zfmodules

build.xml
=> Fix: No need to change the owner all the time

module/Application/test/ApplicationTest/Integration/Controller/ContributorsControllerTest.php, module/Application/test/ApplicationTest/Integration/Controller/IndexControllerTest.php, module/Application/test/ApplicationTest/Integration/Controller/SearchControllerTest.php, module/User/test/UserTest/Integration/Controller/UserControllerTest.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/ModuleControllerTest.php, module/ZfModule/test/ZfModuleTest/Integration/Controller/UserControllerTest.php
=> Fix: Assert route names

README.md
This PR
Related to #491.
:information_desk_person: It seems that we already have Scrutinizer up and running, why not show the badges already?
=> Enhancement: Add Scrutinizer badges

CONTRIBUTING.md, Makefile
:exclamation: Blocked by #499.
This PR
:information_desk_person: Now it's easier than ever to fix coding style issues or run the tests, just run
```
$ make cs
```
or 
```
$ make test
```
=> Enhancement: Add Makefile with cs and test targets

.php_cs, config/autoload/cache.local.php.dist, config/autoload/github.local.php.dist, config/development.config.php.dist
=> Fix: Make sure to fix *.php.dist, too
