zendframework/modules.zendframework.com

- module/Application/src/Application/Service/RepositoryRetriever.php
- module/Application/test/ApplicationTest/Service/RepositoryRetrieverTest.php
- module/ZfModule/src/ZfModule/Controller/IndexController.php
- module/ZfModule/view/zf-module/index/view.phtml
re-added try catch to github retreiver to reflect github exceptions not to the consumer.
this fixes #302 
/cc @GeeH
> Fix: added error catch in github retreiver service

- module/ZfModule/src/ZfModule/View/Helper/ComposerView.php
- module/ZfModule/src/ZfModule/View/Helper/ModuleDescription.php
- module/ZfModule/src/ZfModule/View/Helper/ModuleView.php
- module/ZfModule/src/ZfModule/View/Helper/NewModule.php
- module/ZfModule/src/ZfModule/View/Helper/OwnerModuleList.php
This removes unused methods inside the viewhelper
> Fix: Removed unused methods inside ViewHelpers

- composer.lock
> Fix: composer.lock never seems up to date

- module/ZfModule/src/ZfModule/Controller/IndexControllerFactory.php
- module/ZfModule/src/ZfModule/Module.php
> Fix: Remove unused imports

- module/Application/view/layout/layout-small-header.phtml
- module/Application/view/layout/layout.phtml
- module/User/view/user/helper/user-organizations.phtml
- module/User/view/zfc-user/user/index.phtml
- public/.htaccess
Removed rewrite base - not necessary and makes it easier for contributors to run this repo locally without forced to setup a virtual host.
> Fix: removed rewrite base

- config/autoload/htmlpurifier.global.php
> Fix: added purifier config + cache dir

- module/Application/view/application/index/index.phtml
- module/Application/view/application/index/pagination.phtml
- module/Application/view/layout/layout-small-header.phtml
- module/Application/view/layout/layout.phtml
- module/User/view/user/helper/user-organizations.phtml
- module/User/view/zfc-user/user/index.phtml
- module/ZfModule/view/zf-module/helper/new-module.phtml
- module/ZfModule/view/zf-module/index/index.phtml
- module/ZfModule/view/zf-module/index/view.phtml
> Fix: Actually use short-array syntax in views as well

- module/Application/view/application/index/pagination.phtml
- module/Application/view/layout/layout-small-header.phtml
- module/Application/view/layout/layout.phtml
I don't see a need for them, do you?
> Fix: Remove HTML comments from views

- module/Application/config/module.config.php
- module/Application/src/Application/Controller/IndexController.php
- module/Application/view/application/index/index.phtml
- module/Application/view/application/index/pagination.phtml
- module/Application/view/application/search/index.phtml
> Fix: removed router url params added query params

- composer.json
- config/application.config.php
- module/Application/src/Application/Service/RepositoryRetriever.php
- module/Application/test/ApplicationTest/Service/RepositoryRetrieverTest.php
- module/ZfModule/src/ZfModule/Controller/IndexController.php
- module/ZfModule/view/zf-module/index/view.phtml
github markdown support
fixes #169 
fixes #156
> [WIP] feature/parsedown

- .travis.yml
as composer yells everytime outdated version
> Feature: added composer self update

- module/ZfModule/src/ZfModule/Controller/IndexController.php
as explained here https://github.com/EvanDotPro/EdpGithub/issues/23
the markdown request (POST) needs to be called last as it destroys the normal requests
> HOTFIX: changed github api call order

- config/autoload/scn-social-auth.global.php
> Enhancement: Reduced the GitHub Permissions to working minimum

- module/ZfModule/src/ZfModule/View/Helper/ComposerView.php
- module/ZfModule/view/zf-module/index/view.phtml
if we request the composer file allready we should display it.
this fixes also the text display issue with indentation when using the ``pre`` element
> Feature: added composer to view

- module/User/view/user/helper/new-users.phtml
> Fix: Changed escape to correct escape attr helper

- module/ZfModule/src/ZfModule/Module.php
See https://github.com/zendframework/modules.zendframework.com/blob/master/module/Application/src/Application/Module.php#L18-L20.
> Fix: Attach ModuleRouteListener only once

- module/ZfModule/src/ZfModule/Entity/Module.php
- module/ZfModule/test/ZfModuleTest/Entity/ModuleTest.php
> Fix: Entity test

- module/User/config/module.config.php
- module/User/src/User/Mapper/UserFactory.php
- module/User/src/User/Module.php
- module/User/test/UserTest/Integration/Mapper/UserTest.php
> Enhancement: Extract class for User\Mapper\User factory

- module/Application/view/application/search/index.phtml
- module/User/view/zfc-user/user/index.phtml
- module/ZfModule/src/ZfModule/Entity/Module.php
- module/ZfModule/view/zf-module/helper/new-module.phtml
> Fix: Add/fix/update comments for ZfModule\Entity\Module

- module/Application/view/layout/layout-small-header.phtml
- module/Application/view/layout/layout.phtml
- module/User/src/User/Entity/User.php
- module/User/test/UserTest/Entity/UserTest.php
- module/User/view/user/helper/new-users.phtml
- module/User/view/zfc-user/user/index.phtml
> Enhancement: Add tests for ZfModule\Entity\User

- data/sql/0.sql
fixes #306 
and #251 can be closed?
> Fix: added auto_increment to sql dump

- module/ZfModule/src/ZfModule/Controller/IndexController.php
as the pr is merged https://github.com/EvanDotPro/EdpGithub/issues/23 steps from  #339 are no longer necessary
> Fix: Removed hint

- module/ZfModule/test/ZfModuleTest/Integration/Mapper/ModuleTest.php
> Fix: No need to manually set primary key anymore

- module/Application/view/layout/footer.phtml
- module/Application/view/layout/layout.phtml
This PR
Sorry, @Ocramius, meant to actually commit this into #403, but forgot!
> Fix: Inline partial

- .gitignore
> Fix: Clean up .gitignore

- module/ZfModule/src/ZfModule/Entity/Module.php
- module/ZfModule/src/ZfModule/Entity/ModuleInterface.php
- module/ZfModule/test/ZfModuleTest/Entity/ModuleTest.php
- added missing doctypes to the module interface
- removes return types from interface
- removes fluid style from module entity
> Feature: Removed fluid interface from module entity/interface

- module/Application/view/application/index/index.phtml
- module/ZfModule/view/zf-module/helper/module-description.phtml
Change target in _blank
Now github does not override zf modules site
> "Show module on github" target blank

- module/User/view/zfc-user/user/index.phtml
> Fixed thumbnail size into user/index template

- composer.json
- composer.lock
as @gianarb added a version to ``evandotpro/edp-github`` we can add it to composer
> Enhancement: Added github version to composer 

- module/User/view/user/helper/user-organizations.phtml
> Fix organization's img size

- module/Application/src/Application/Controller/ContributorsController.php
This PR
Follows https://github.com/zendframework/modules.zendframework.com/pull/447#issuecomment-76898574.
> Enhancement: Shuffle list of contributors

- build.xml
> Fix: Sudo not required anymore

- composer.json
- composer.lock
This PR
:bulb: Had some problems because of weird error messages from Composer, but worked around it.
> Your requirements could not be resolved to an installable set of packages.
/cc @ins0 
Blocks #421.
> Enhancement: Update phpunit/phpunit to ~4.5

- build.xml
> Fix: Reset before pulling in changes

- module/Application/view/layout/layout.phtml
follow #479
account owner: @EvanDotPro 
access: @gianarb
> Feature: added google analytics code

- module/ZfModule/test/ZfModuleTest/Integration/Controller/ModuleControllerTest.php
This PR
Relates to https://github.com/zendframework/modules.zendframework.com/pull/462#issuecomment-77376713.
> Enhancement: Assert ModuleController::viewAction() is not dispatched to

- .travis.yml
- composer.lock
This PR
Follows https://github.com/composer/composer/pull/4219.
> Fix: Validate composer.json and composer.lock on Travis
